server:
  port: 80

spring:
  application:
    name: whoistobuy-gateway
  main:
    web-application-type: reactive

  cloud:
    loadbalancer:
      configurations: health-check
    discovery:
      client:
        simple:
          instances:
            whoistobuy-auth:
              - secure: false
                port: 8080
                host: localhost
                serviceId: whoistobuy-auth
                instanceId: whoistobuy-auth-1
            whoistobuy-shop:
              - secure: false
                port: 8081
                host: localhost
                serviceId: whoistobuy-shop
                instanceId: whoistobuy-shop-1

    gateway:

      routes:
        - id: auth
          uri: lb://whoistobuy-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: items
          uri: lb://whoistobuy-shop
          predicates:
            - Path=/api/v1/items/**
#
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000/"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT


logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id:
